MotorMart/MotorMart/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^\/$|^home\/$",home,name="home"),

    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("profilo/", profile, name='profile'),
    path("profilo/<pk>", get_profile, name='get_profile'),

    path("annunci/", include("annunci.urls")),
    path("recensione/", include("recensioni.urls")),
    path("proposta/", include("proposte.urls")),
    path("chat/", include("chat.urls")),
]

MotorMart/annunci/urls.py
from django.urls import path
from .views import *


app_name = "annunci"

urlpatterns = [
    path("", ListingsView.as_view(), name="annunci_list"),
    path("search", search, name="search"),
    path("inserisci/", create, name="create"),
    path("modifica/<int:pk>", edit, name="edit"),
    path("elimina/<int:pk>", delete, name="delete"),
    path("acquista/<int:pk>", buy, name="buy"),
    path("<int:pk>", details, name="details"),
]

MotorMart/chat/urls.py
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views

app_name = "chat"

urlpatterns = [
    path('chat_list', views.chat_list, name='chat_list'),  
    path('<int:chat_id>', views.chat_view, name='chat_view'),
    path('create_chat/<int:user_id>/', views.create_chat, name='create_chat'),
]

MotorMart/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MotorMart</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href='{% static "./css/bootstrap.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/elegant-icons.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/nice-select.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/magnific-popup.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/jquery-ui.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/owl.carousel.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/slicknav.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/style.css" %}' type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="./"><img src="{% static "./img/logo-new.png" %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-10">
                    <div class="header__nav">
                        <nav class="header__menu">
                            <ul>
                                {% if user.is_authenticated %}
                                    <li>Benvenuto, {{ user.username }}</li>
                                {% endif %}
                                <li class="active"><a href="./">Home</a></li>
                                <li><a href="{% url 'annunci:annunci_list' %}">Annunci</a></li>
                                <li><a href="{% url 'profile' %}">Profilo</a></li>
                                <li><a href="{% url 'chat:chat_list' %}">Chat</a></li>
                            </ul>
                        </nav>

                        {% if user.is_authenticated %}
                            <div class="header__nav__widget">
                                <form method="get" action="{% url 'annunci:create' %}">
                                    <button class="primary-btn">Crea annuncio</button>
                                </form>
                            </div>
                            <div class="header__nav__widget">
                                <form id="logout-form" method="post" action="{% url 'logout' %}">
                                    {% csrf_token %}
                                    <button class="primary-btn">Logout</button>
                                </form>
                            </div>
                        
                        {% else %}
                            <div class="header__nav__widget">
                                <a href="{% url 'login' %}" class="primary-btn">Login</a>
                                <a href="{% url 'register' %}" class="primary-btn">Registrazione</a>
                            </div>
                        {% endif %}

                    </div>
                </div>
            </div>
            <div class="canvas__open">
                <span class="fa fa-bars"></span>
            </div>
        </div>
    </header>
    <!-- Header Section End -->

    <!-- Hero Section Begin -->
    <section class="hero spad set-bg" data-setbg="{% static "./img/hero-bg-created.jpg" %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-7">
                    <div class="hero__text">
                        <div class="hero__text__title">
                            <span>Trova la tua auto ideale</span>
                        </div>
                    </div>
                </div>

                <div class="col-lg-5">
                    <div class="hero__tab">
                        <div class="tab-content">
                            <div class="tab-pane active" id="tabs-1" role="tabpanel">
                                <div class="hero__tab__form">
                                    
                                    <form method="POST" action="{% url 'annunci:search' %}">
                                        {% csrf_token %}
                                        <div class="select-list">
                                            <div class="select-list-item">
                                                <p>Anno</p>
                                                <select name="anno">
                                                    <option data-display=""></option>
                                                    {% for anno in anni %}
                                                        <option value="{{anno}}">{{anno}}</option>
                                                    {%endfor%}
                                                </select>
                                            </div>
                                            <div class="select-list-item">
                                                <p>Marchio</p>
                                                <select name="marchio">
                                                    <option data-display=" "></option>
                                                    {% for marca in marche %}
                                                        <option value="{{marca}}">{{marca}}</option>
                                                    {%endfor%}
                                                </select>
                                            </div>
                                            <div class="select-list-item">
                                                <p>Modello</p>
                                                <select name="modello">
                                                    <option data-display=" "></option>
                                                    {% for modello in modelli %}
                                                        <option value="{{modello}}">{{modello}}</option>
                                                    {%endfor%}
                                                </select>
                                            </div>
                                            <div class="select-list-item">
                                                <p>Chilometraggio</p>
                                                <select name="chilometraggio">
                                                    <option data-display=" "></option>
                                                    <option value="0-25000">0-25000</option>
                                                    <option value="25001-50000">25001-50000</option>
                                                    <option value="50001-75000">50001-75000</option>
                                                    <option value="75001-100000">75001-100000</option>
                                                    <option value="100001">100000+</option>
                                                </select>
                                            </div>
                                            <div class="select-list-item">
                                                <p>Prezzo</p>
                                                <select name="prezzo">
                                                    <option data-display=" ">Prezzo</option>
                                                    <option value="0-25000">€ &lt;25000</option>
                                                    <option value="25001-50000">€ 25001 - € 50000</option>
                                                    <option value="50001-75000">€ 50001 - € 75000</option>
                                                    <option value="75001-100000">€ 75001 - € 100000</option>
                                                    <option value="100001">€ 100000+</option>
                                                </select>
                                            </div>
                                        </div>
                                        
                                        <button type="submit" class="site-btn">Cerca</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->


    <!-- Js Plugins -->
    <script src="{% static "./js/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "./js/bootstrap.min.js" %}"></script>
    <script src="{% static "./js/jquery.nice-select.min.js" %}"></script>
    <script src="{% static "./js/jquery-ui.min.js" %}"></script>
    <script src="{% static "./js/jquery.magnific-popup.min.js" %}"></script>
    <script src="{% static "./js/mixitup.min.js" %}"></script>
    <script src="{% static "./js/jquery.slicknav.js" %}"></script>
    <script src="{% static "./js/owl.carousel.min.js" %}"></script>
    <script src="{% static "./js/main.js" %}"></script>
</body>

</html>

MotorMart/templates/profile.html
<!DOCTYPE html>
<html lang="zxx">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MotorMart - Profilo</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href='{% static "./css/bootstrap.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/elegant-icons.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/nice-select.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/magnific-popup.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/jquery-ui.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/owl.carousel.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/slicknav.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/style.css" %}' type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="{% url 'home' %}"><img src="{% static "./img/logo-new.png" %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-10">
                    <div class="header__nav">
                        <nav class="header__menu">
                            <ul>
                                {% if user.is_authenticated %}
                                    <li>Benvenuto, {{ user.username }}</li>
                                {% endif %}
                                <li><a href="{% url 'home' %}">Home</a></li>
                                <li><a href="{% url 'annunci:annunci_list' %}">Annunci</a></li>
                                <li class="active"><a href="{% url 'profile' %}">Profilo</a></li>
                                <li><a href="{% url 'chat:chat_list' %}">Chat</a></li>
                            </ul>
                        </nav>

                        {% if user.is_authenticated %}
                            <div class="header__nav__widget">
                                <form method="get" action="{% url 'annunci:create' %}">
                                    <button class="primary-btn">Crea annuncio</button>
                                </form>
                            </div>
                            <div class="header__nav__widget">
                                <form id="logout-form" method="post" action="{% url 'logout' %}">
                                    {% csrf_token %}
                                    <button class="primary-btn">Logout</button>
                                </form>
                            </div>
                        
                        {% else %}
                            <div class="header__nav__widget">
                                <a href="{% url 'login' %}" class="primary-btn">Login</a>
                                <a href="{% url 'register' %}" class="primary-btn">Registrazione</a>
                            </div>
                        {% endif %}

                    </div>
                </div>
            </div>
            <div class="canvas__open">
                <span class="fa fa-bars"></span>
            </div>
        </div>
    </header>
    <!-- Header Section End -->



    <!-- Car Section Begin -->
    <!-- Car Section Begin -->
<section class="car spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <h3 style="padding-bottom: 25px;">Annunci Inseriti</h3>
                <div class="row">
                    {% for a in annunci %}
                    <div class="col-lg-4 col-md-4">
                        <div class="car__item">
                            <div class="car__item__pic__slider owl-carousel">
                                <img src="{{ MEDIA_URL }}{{ a.immagine }}" alt="">
                            </div>
                            <div class="car__item__text">
                                <div class="car__item__text__inner">
                                    <div class="label-date">{{ a.anno }}</div>
                                    <h5><a href="{% url 'annunci:details' a.pk %}">{{ a.marca }} - {{ a.modello }}</a></h5>
                                    <ul>
                                        <li><span>{{ a.chilometraggio }}</span> km</li>
                                        <li><span>{{ a.cambio }}</span></li>
                                        <li><span>{{ a.potenza }}</span> cv</li>
                                    </ul>
                                </div>
                                <div class="car__item__price">
                                    <span class="car-option">Prezzo</span>
                                    <h6>€ {{ a.prezzo }}</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Car Section End -->

<!-- Review Section Begin -->
<section class="reviews spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <h3 style="padding-bottom: 25px;">Recensioni</h3>
                <div class="row">
                    {% for r in recensioni %}
                    <div class="col-lg-4 col-md-4">
                        <div class="car__item">
                            <div class="car__item__text">
                                <div class="car__item__text__inner">
                                    <div class="label-date">{{ r.data_inserimento |date:"d M Y" }}</div>
                                    <h5>Utente: {{ r.recensore }}</a></h5>
                                    <ul>
                                        <li><span>{{ r.descrizione }}</span></li>
                                    </ul>
                                </div>
                                <div class="car__item__price">
                                    <span class="car-option">Rating</span>
                                    <h6> {{ r.rating }}/5</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Review Section End -->

    <!-- Car Section End -->

    <!-- Js Plugins -->
    <script src="{% static "./js/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "./js/bootstrap.min.js" %}"></script>
    <script src="{% static "./js/jquery.nice-select.min.js" %}"></script>
    <script src="{% static "./js/jquery-ui.min.js" %}"></script>
    <script src="{% static "./js/jquery.magnific-popup.min.js" %}"></script>
    <script src="{% static "./js/mixitup.min.js" %}"></script>
    <script src="{% static "./js/jquery.slicknav.js" %}"></script>
    <script src="{% static "./js/owl.carousel.min.js" %}"></script>
    <script src="{% static "./js/main.js" %}"></script>
</body>

</html>

MotorMart/templates/user_create.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MotorMart</title>
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href='{% static "./css/bootstrap.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/elegant-icons.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/nice-select.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/magnific-popup.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/jquery-ui.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/owl.carousel.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/slicknav.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/style.css" %}' type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="{% url 'home' %}"><img src="{% static "./img/logo-new.png" %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-10">
                    <div class="header__nav">
                        <nav class="header__menu">
                            <ul>
                                {% if user.is_authenticated %}
                                    <li>Benvenuto, {{ user.username }}</li>
                                {% endif %}
                                <li><a href="{% url 'home' %}">Home</a></li>
                                <li><a href="{% url 'annunci:annunci_list' %}">Annunci</a></li>
                                <li><a href="{% url 'profile' %}">Profilo</a></li>
                                <li><a href="{% url 'chat:chat_list' %}">Chat</a></li>
                            </ul>
                        </nav>

                        {% if user.is_authenticated %}
                            <div class="header__nav__widget">
                                <form method="get" action="{% url 'annunci:create' %}">
                                    <button class="primary-btn">Crea annuncio</button>
                                </form>
                            </div>
                            <div class="header__nav__widget">
                                <form id="logout-form" method="post" action="{% url 'logout' %}">
                                    {% csrf_token %}
                                    <button class="primary-btn">Logout</button>
                                </form>
                            </div>
                        
                        {% else %}
                            <div class="header__nav__widget">
                                <a href="{% url 'login' %}" class="primary-btn">Login</a>
                                <a href="{% url 'register' %}" class="primary-btn">Registrazione</a>
                            </div>
                        {% endif %}

                    </div>
                </div>
            </div>
            <div class="canvas__open">
                <span class="fa fa-bars"></span>
            </div>
        </div>
    </header>
    <!-- Header Section End -->

    <!-- Hero Section Begin -->
    <section class="hero spad set-bg" data-setbg="{% static "./img/hero-bg-created.jpg" %}">
        <div class="container">
            <div class="row">
                
                <div class="col-lg-5">
                    <div class="hero__tab">
                        <ul class="nav nav-tabs" role="tablist">
                            
                            
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tabs-1" role="tabpanel">
                                <div class="hero__tab__form">
                                    <center>
                                        {% if "notok" in request.GET.auth %}
                                            <div class="alert alert-danger" role="alert">
                                            Effettuare il login per accedere al servizio scelto
                                            </div>
                                        {% endif %}
                                        <form method="post"> {% csrf_token %}
                                          {{form}}
                                          <input type="submit" class="btn btn-success" value="Registrati ora!">
                                        </form>
                                      </center>
                                </div>
                            </div>
                        
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->


    <!-- Js Plugins -->
    <script src="{% static "./js/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "./js/bootstrap.min.js" %}"></script>
    <script src="{% static "./js/jquery.nice-select.min.js" %}"></script>
    <script src="{% static "./js/jquery-ui.min.js" %}"></script>
    <script src="{% static "./js/jquery.magnific-popup.min.js" %}"></script>
    <script src="{% static "./js/mixitup.min.js" %}"></script>
    <script src="{% static "./js/jquery.slicknav.js" %}"></script>
    <script src="{% static "./js/owl.carousel.min.js" %}"></script>
    <script src="{% static "./js/main.js" %}"></script>
</body>

</html>