MotorMart/MotorMart/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^\/$|^home\/$",home,name="home"),

    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("profilo/", profile, name='profile'),
    path("profilo/<pk>", get_profile, name='get_profile'),

    path("annunci/", include("annunci.urls")),
    path("recensione/", include("recensioni.urls")),
    path("proposta/", include("proposte.urls")),
    path("chat/", include("chat.urls")),
]

MotorMart/annunci/urls.py
from django.urls import path
from .views import *


app_name = "annunci"

urlpatterns = [
    path("", ListingsView.as_view(), name="annunci_list"),
    path("search", search, name="search"),
    path("inserisci/", create, name="create"),
    path("modifica/<int:pk>", edit, name="edit"),
    path("elimina/<int:pk>", delete, name="delete"),
    path("acquista/<int:pk>", buy, name="buy"),
    path("<int:pk>", details, name="details"),
]

MotorMart/chat/urls.py
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views

app_name = "chat"

urlpatterns = [
    path('chat_list', views.chat_list, name='chat_list'),  
    path('<int:chat_id>', views.chat_view, name='chat_view'),
    path('create_chat/<int:user_id>/', views.create_chat, name='create_chat'),
]

MotorMart/proposte/urls.py
from django.urls import path
from . import views

app_name = "proposte"

urlpatterns = [
    path('<int:pk>/', views.listing_detail, name='proposals'),
    path('accept/<int:proposal_id>/', views.accept_proposal, name='accept_proposal'),
    path('reject/<int:proposal_id>/', views.reject_proposal, name='reject_proposal'),
]

MotorMart/recensioni/urls.py
from django.urls import path
from .views import *

app_name = "recensioni"

urlpatterns = [
    path("inserisci/<int:pk>", review, name='review'),
]

MotorMart/annunci/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.exceptions import ValidationError


class Annuncio(models.Model):

    cambio_opzioni = [
        ('automatico', 'Automatico'),
        ('manuale', 'Manuale'),
    ]

    stato_opzioni = [
        ('ottimo', 'Ottimo'),
        ('buono', 'Buono'),
        ('danneggiato', 'Danneggiato'),
    ]

    carburante_opzioni = [
        ('benzina', 'Benzina'),
        ('diesel', 'Diesel'),
        ('GPL', 'GPL'),
        ('metano', 'Metano'),
        ('elettrico', 'Elettrico')
    ]

    marca = models.CharField(max_length=20)
    modello = models.CharField(max_length=30)
    anno = models.IntegerField()
    prezzo = models.IntegerField()
    chilometraggio = models.IntegerField()
    potenza = models.IntegerField()
    cilindrata = models.IntegerField()
    stato = models.CharField(max_length=20, choices=stato_opzioni)
    carburante = models.CharField(max_length=20, choices=carburante_opzioni)
    cambio = models.CharField(max_length=20, choices=cambio_opzioni)
    colore = models.CharField(max_length=30)
    immagine = models.ImageField(upload_to ='static/img/uploads') 
    descrizione = models.CharField(max_length=200)
    utente = models.ForeignKey(User, on_delete=models.CASCADE)
    data_inserimento = models.DateTimeField(default=timezone.now, blank=True)
    venduto = models.BooleanField(null=True, blank=True)
    compratore = models.IntegerField(null=True, blank=True)
    prezzo_acquisto = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.modello

MotorMart/annunci/forms.py
from django import forms
from .models import Annuncio


class CreaAnnuncio(forms.ModelForm):

    class Meta:
        model = Annuncio
        fields = [
            'marca', 'modello', 'anno', 'prezzo', 'chilometraggio', 'potenza',
            'cilindrata', 'stato', 'carburante', 'cambio', 'colore', 'descrizione', 'immagine'
        ]

    def clean(self):
        cleaned_data = super().clean()
        anno = cleaned_data.get('anno')
        prezzo = cleaned_data.get('prezzo')
        chilometraggio = cleaned_data.get('chilometraggio')
        potenza = cleaned_data.get('potenza')
        cilindrata = cleaned_data.get('cilindrata')

        if anno is not None and anno < 1900:
            self.add_error('anno', 'L\'anno deve essere un numero positivo.')

        if prezzo is not None and prezzo <= 0:
            self.add_error('prezzo', 'Il prezzo deve essere un numero positivo.')

        if chilometraggio is not None and chilometraggio <= 0:
            self.add_error('chilometraggio', 'Il chilometraggio deve essere un numero positivo.')

        if potenza is not None and potenza <= 0:
            self.add_error('potenza', 'La potenza deve essere un numero positivo.')

        if cilindrata is not None and cilindrata <= 0:
            self.add_error('cilindrata', 'La cilindrata deve essere un numero positivo.')

        marca = cleaned_data.get('marca')
        modello = cleaned_data.get('modello')

        if marca:
            cleaned_data['marca'] = marca.capitalize()

        if modello:
            cleaned_data['modello'] = modello.capitalize()

        return cleaned_data

MotorMart/annunci/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic.list import ListView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *


class ListingsView(ListView):
    model = Annuncio
    template_name = "annunci/cars.html"
    ordering = ['marca', 'modello']
    context_object_name = 'annunci'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        marche = set()
        modelli = set()
        anni = set()

        for annuncio in Annuncio.objects.all():
            marche.add(annuncio.marca)
            modelli.add(annuncio.modello)
            anni.add(annuncio.anno)

        context['marche'] = sorted(list(marche))
        context['modelli'] = sorted(list(modelli)) 
        context['anni'] =  sorted(list(anni), reverse=True) 

        return context


@login_required
def details(request, pk):
    annuncio = Annuncio.objects.get(id=pk)
    ctx = {"annuncio": annuncio}
    return render(request, "annunci/details.html", ctx)



def search(request):
    if request.method == "POST":

        anno = request.POST.get('anno')
        marchio = request.POST.get('marchio')
        modello = request.POST.get('modello')
        chilometraggio = request.POST.get('chilometraggio')
        prezzo = request.POST.get('prezzo')

        filter_kwargs = {}
        if anno:
            filter_kwargs['anno'] = anno
        if marchio:
            filter_kwargs['marca'] = marchio
        if modello:
            filter_kwargs['modello'] = modello
        if chilometraggio:
            try:
                if '-' in chilometraggio:
                    min_chilometraggio, max_chilometraggio = map(int, chilometraggio.split('-'))
                    filter_kwargs['chilometraggio__gte'] = min_chilometraggio
                    filter_kwargs['chilometraggio__lte'] = max_chilometraggio
                else:
                    filter_kwargs['chilometraggio__gte'] = int(chilometraggio)
            except ValueError:
                pass
        if prezzo:
            try:
                if '-' in prezzo:
                    min_prezzo, max_prezzo = map(int, prezzo.split('-'))
                    filter_kwargs['prezzo__gte'] = min_prezzo
                    filter_kwargs['prezzo__lte'] = max_prezzo
                else:
                    filter_kwargs['prezzo__gte'] = int(prezzo)
            except ValueError:
                pass

        annunci_filtered = Annuncio.objects.filter(**filter_kwargs).order_by('marca','modello')

        marche = sorted({annuncio.marca for annuncio in Annuncio.objects.all()})
        modelli = sorted({annuncio.modello for annuncio in Annuncio.objects.all()})
        anni = sorted({annuncio.anno for annuncio in Annuncio.objects.all()}, reverse=True)

        context = {
            'object_list': annunci_filtered,
            'marche': marche,
            'modelli': modelli,
            'anni': anni
        }

        return render(request, "annunci/cars.html", context)


@login_required
def create(request):
    if request.method == 'POST':
        form = CreaAnnuncio(request.POST, request.FILES)
        if form.is_valid():
            annuncio = form.save(commit=False)
            annuncio.utente = request.user
            annuncio.save()
            messages.success(request, "Annuncio inserito correttamente")
            return redirect('annunci:annunci_list')
        else:
            messages.error(request, "Errore nell'inserimento dell'annuncio")
            return redirect('annunci:annunci_list')
    else:
        form = CreaAnnuncio()
        return render(request, "annunci/create.html", {'form': form})



@login_required
def edit(request, pk):

    annuncio = get_object_or_404(Annuncio, pk=pk)

    if annuncio.utente != request.user:
        messages.error(request, "Non hai i permessi per modificare questo annuncio")
        return redirect('annunci:annunci_list')

    if request.method == 'POST':
        form = CreaAnnuncio(request.POST, request.FILES, instance=annuncio)
        if form.is_valid():
            annuncio = form.save(commit=False)
            annuncio.utente = request.user
            annuncio.save()
            messages.success(request, "Annuncio modificato correttamente")
            return redirect('annunci:details', pk=annuncio.pk)
    else:
        form = CreaAnnuncio(instance=annuncio)

    return render(request, "annunci/edit.html", {'form': form})


@login_required
def delete(request, pk):
    annuncio = get_object_or_404(Annuncio, pk=pk)
    
    if annuncio.utente != request.user:
        messages.error(request, "Non hai i permessi per modificare questo annuncio")
        return redirect('annunci:annunci_list')
    
    if request.method == "POST":
        annuncio.delete()
        messages.success(request, "Annuncio eliminato correttamente")
        return redirect('annunci:annunci_list')

    return render(request, "annunci/delete.html" , {'annuncio': annuncio})


@login_required
def buy(request,pk):

    annuncio = get_object_or_404(Annuncio, pk=pk)

    if annuncio.utente == request.user:
        messages.error(request, "Non hai i permessi per modificare questo annuncio")
        return redirect('annunci:details', pk=annuncio.pk)
    
    if annuncio.venduto == True:
        messages.error(request, "Auto già venduta")
        return redirect('annunci:details', pk=annuncio.pk)
    
    if request.method == "POST":

        annuncio.venduto = True
        annuncio.prezzo_acquisto = annuncio.prezzo
        annuncio.compratore = request.user.id
        annuncio.save()

        messages.error(request, "Auto acquistata correttamente")
        return redirect('annunci:details', pk=annuncio.pk)
    
    return render(request, "annunci/buy.html" , {'annuncio': annuncio})

MotorMart/annunci/templates/annunci/buy.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MotorMart - Acquisto</title>
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href='{% static "./css/bootstrap.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/elegant-icons.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/nice-select.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/magnific-popup.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/jquery-ui.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/owl.carousel.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/slicknav.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/style.css" %}' type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="{% url 'home' %}"><img src="{% static "./img/logo-new.png" %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-10">
                    <div class="header__nav">
                        <nav class="header__menu">
                            <ul>
                                {% if user.is_authenticated %}
                                    <li>Benvenuto, {{ user.username }}</li>
                                {% endif %}
                                <li><a href="{% url 'home' %}">Home</a></li>
                                <li><a href="{% url 'annunci:annunci_list' %}">Annunci</a></li>
                                <li><a href="{% url 'profile' %}">Profilo</a></li>
                                <li><a href="{% url 'chat:chat_list' %}">Chat</a></li>
                            </ul>
                        </nav>

                        {% if user.is_authenticated %}
                            <div class="header__nav__widget">
                                <form method="get" action="{% url 'annunci:create' %}">
                                    <button class="primary-btn">Crea annuncio</button>
                                </form>
                            </div>
                            <div class="header__nav__widget">
                                <form id="logout-form" method="post" action="{% url 'logout' %}">
                                    {% csrf_token %}
                                    <button class="primary-btn">Logout</button>
                                </form>
                            </div>
                        
                        {% else %}
                            <div class="header__nav__widget">
                                <a href="{% url 'login' %}" class="primary-btn">Login</a>
                                <a href="{% url 'register' %}" class="primary-btn">Registrazione</a>
                            </div>
                        {% endif %}

                    </div>
                </div>
            </div>
            <div class="canvas__open">
                <span class="fa fa-bars"></span>
            </div>
        </div>
    </header>
    <!-- Header Section End -->

    <!-- Hero Section Begin -->
    <section class="hero spad set-bg" data-setbg="{% static "./img/hero-bg-created.jpg" %}">
        <div class="container">
            <div class="row">
                
                <div class="col-lg-5">
                    <div class="hero__tab">
                        <ul class="nav nav-tabs" role="tablist">
                            
                            
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tabs-1" role="tabpanel">
                                <div class="hero__tab__form">
                                    <center>
                                        <h3>Acquista auto</h3>
                                        <p>Sicuro di voler acquistare l'automobile "{{ annuncio.marca }} {{ annuncio.modello }} {{ annuncio.anno }}"?</p>
                                        <form method="post">
                                            {% csrf_token %}
                                            <button type="submit" class="primary-btn">Conferma</button>
                                        </form>
                                        <a href="{% url 'annunci:annunci_list' %}">Annulla</a>
                                      </center>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->

    <!-- Js Plugins -->
    <script src="{% static "./js/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "./js/bootstrap.min.js" %}"></script>
    <script src="{% static "./js/jquery.nice-select.min.js" %}"></script>
    <script src="{% static "./js/jquery-ui.min.js" %}"></script>
    <script src="{% static "./js/jquery.magnific-popup.min.js" %}"></script>
    <script src="{% static "./js/mixitup.min.js" %}"></script>
    <script src="{% static "./js/jquery.slicknav.js" %}"></script>
    <script src="{% static "./js/owl.carousel.min.js" %}"></script>
    <script src="{% static "./js/main.js" %}"></script>
</body>

</html>

MotorMart/annunci/templates/annunci/details.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MotorMart - Dettagli</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href='{% static "./css/bootstrap.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/elegant-icons.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/nice-select.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/magnific-popup.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/jquery-ui.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/owl.carousel.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/slicknav.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/style.css" %}' type="text/css">

    <style>
        .description-box {
            background-color: #f8f9fa;
            border: 1px solid #e9ecef;
            border-radius: 5px;
            padding: 15px;
            margin-bottom: 20px;
        }
    </style>
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

   <!-- Header Section Begin -->
   <header class="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-2">
                <div class="header__logo">
                    <a href="{% url 'home' %}"><img src="{% static "./img/logo-new.png" %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-10">
                <div class="header__nav">
                    <nav class="header__menu">
                        <ul>
                            {% if user.is_authenticated %}
                                <li>Benvenuto, {{ user.username }}</li>
                            {% endif %}
                            <li><a href="{% url 'home' %}">Home</a></li>
                            <li><a href="{% url 'annunci:annunci_list' %}">Annunci</a></li>
                            <li><a href="{% url 'profile' %}">Profilo</a></li>
                            <li><a href="{% url 'chat:chat_list' %}">Chat</a></li>
                        </ul>
                    </nav>

                    {% if user.is_authenticated %}
                        <div class="header__nav__widget">
                            <form method="get" action="{% url 'annunci:create' %}">
                                <button class="primary-btn">Crea annuncio</button>
                            </form>
                        </div>
                        <div class="header__nav__widget">
                            <form id="logout-form" method="post" action="{% url 'logout' %}">
                                {% csrf_token %}
                                <button class="primary-btn">Logout</button>
                            </form>
                        </div>
                    
                    {% else %}
                        <div class="header__nav__widget">
                            <a href="{% url 'login' %}" class="primary-btn">Login</a>
                            <a href="{% url 'register' %}" class="primary-btn">Registrazione</a>
                        </div>
                    {% endif %}

                </div>
            </div>
        </div>
        <div class="canvas__open">
            <span class="fa fa-bars"></span>
        </div>
    </div>
</header>
<!-- Header Section End -->

    <!-- Breadcrumb End -->
    <div class="breadcrumb-option set-bg" data-setbg="{% static "./img/footer-bg.jpg" %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2> {{annuncio.marca}}  {{annuncio.modello}}</h2>
                        <div class="breadcrumb__links">
                            <a href="{% url 'home' %}"><i class="fa fa-home"></i> Home</a>
                            <a href="{% url 'annunci:annunci_list' %}">Annunci</a>
                            <span>{{annuncio.marca}}  {{annuncio.modello}}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Begin -->

    <!-- Car Details Section Begin -->
    <section class="car-details spad">
        <div class="container">
            <div class="row">

                <div class="col-lg-9">
                    {% if messages %}
                            {% for m in messages %}
                                <center><p class="description-box">{{ m }}</p></center>
                            {% endfor %}
                        {% endif %}
                    <div class="car__details__pic">
                        <div class="car__details__pic__large">
                            <img class="car-big-img" src="{{ MEDIA_URL }}{{ annuncio.immagine }}" alt="">
                        </div>
                        
                    </div>

                    <div class="car__details__info">
                        <ul>
                            <li>Anno: <span>{{annuncio.anno}}</span></li>
                            <li>Chilometraggio: <span>{{annuncio.chilometraggio}}</span> km</li>
                            <li>Potenza: <span>{{annuncio.potenza}}</span> cv</li>
                            <li>Cilindrata: <span>{{annuncio.cilindrata}}</span> &#13220;</li>
                            <li>Carburante: <span>{{annuncio.carburante}}</span></li>
                            <li>Stato: <span>{{annuncio.stato}}</span></li>
                            <li>Cambio: <span>{{annuncio.cambio}}</span></li>
                            <li>Descrizione: <span>{{annuncio.descrizione}}</span></li>
                            <li>Colore: <span>{{annuncio.colore}}</span></li>
                        </ul>


                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="car__details__sidebar">
                        <div class="car__details__sidebar__model">
                            <p>Data: {{annuncio.data_inserimento |date:"d M Y"}}</p>
                            <p>Inserito da: <a href="{% url 'get_profile' annuncio.utente.id %}">{{annuncio.utente}}</a></p>
                        </div>
                        <div class="car__details__sidebar__payment">
                            <ul>
                        
                                <li>Prezzo <span>€ {{annuncio.prezzo}}</span></li>
                            </ul>
                            {% if user.id == annuncio.utente.id %}
                                {% if annuncio.venduto == True %}
                                    <h4>Auto venduta a € {{annuncio.prezzo_acquisto}}</h4>
                                {% endif %}
                                <a href="{% url 'proposte:proposals' annuncio.pk %}" class="primary-btn sidebar-btn"><i class="fa fa-sliders"></i> Proposte d'acquisto</a>
                                <a href="{% url 'annunci:edit' annuncio.pk %}" class="primary-btn sidebar-btn"><i class="fa fa-sliders"></i> Modifica</a>
                                <a href="{% url 'annunci:delete' annuncio.pk %}" class="primary-btn sidebar-btn"><i class="fa fa-sliders"></i> Elimina</a>
                            {% else %}
                                {% if annuncio.venduto == True and request.user.id == annuncio.compratore %}
                                <h4>Hai acquistato questa automobile a € {{annuncio.prezzo_acquisto}}</h4>
                                {% elif annuncio.venduto == True %}
                                <h4>Auto venduta</h4>
                                {% else %}
                                <a href="{% url 'annunci:buy' annuncio.pk %}" class="primary-btn"><i class="fa fa-credit-card"></i> Acquista</a>
                                <a href="{% url 'proposte:proposals' annuncio.pk %}" class="primary-btn sidebar-btn"><i class="fa fa-sliders"></i> Proposta d'acquisto</a>
                                <a href="{% url 'chat:create_chat' annuncio.utente.id %}" class="primary-btn sidebar-btn"><i class="fa fa-money"></i> Contatta il venditore</a>
                                <a href="{% url "recensioni:review" annuncio.pk %}" class="primary-btn sidebar-btn"><i class="fa fa-money"></i> Recensisci il venditore</a>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Car Details Section End -->

    <!-- Js Plugins -->
    <script src="{% static "./js/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "./js/bootstrap.min.js" %}"></script>
    <script src="{% static "./js/jquery.nice-select.min.js" %}"></script>
    <script src="{% static "./js/jquery-ui.min.js" %}"></script>
    <script src="{% static "./js/jquery.magnific-popup.min.js" %}"></script>
    <script src="{% static "./js/mixitup.min.js" %}"></script>
    <script src="{% static "./js/jquery.slicknav.js" %}"></script>
    <script src="{% static "./js/owl.carousel.min.js" %}"></script>
    <script src="{% static "./js/main.js" %}"></script>
</body>

</html>