MotorMart/MotorMart/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^\/$|^home\/$",home,name="home"),

    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("profilo/", profile, name='profile'),
    path("profilo/<pk>", get_profile, name='get_profile'),

    path("annunci/", include("annunci.urls")),
    path("recensione/", include("recensioni.urls")),
    path("proposta/", include("proposte.urls")),
    path("chat/", include("chat.urls")),
]

MotorMart/annunci/urls.py
from django.urls import path
from .views import *


app_name = "annunci"

urlpatterns = [
    path("", ListingsView.as_view(), name="annunci_list"),
    path("search", search, name="search"),
    path("inserisci/", create, name="create"),
    path("modifica/<int:pk>", edit, name="edit"),
    path("elimina/<int:pk>", delete, name="delete"),
    path("acquista/<int:pk>", buy, name="buy"),
    path("<int:pk>", details, name="details"),
]

MotorMart/chat/urls.py
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views

app_name = "chat"

urlpatterns = [
    path('chat_list', views.chat_list, name='chat_list'),  
    path('<int:chat_id>', views.chat_view, name='chat_view'),
    path('create_chat/<int:user_id>/', views.create_chat, name='create_chat'),
]

MotorMart/proposte/urls.py
from django.urls import path
from . import views

app_name = "proposte"

urlpatterns = [
    path('<int:pk>/', views.listing_detail, name='proposals'),
    path('accept/<int:proposal_id>/', views.accept_proposal, name='accept_proposal'),
    path('reject/<int:proposal_id>/', views.reject_proposal, name='reject_proposal'),
]

MotorMart/proposte/models.py
from django.db import models
from annunci.models import Annuncio
from django.contrib.auth.models import User
from django.utils import timezone


class Proposta(models.Model):
    annuncio = models.ForeignKey(Annuncio, on_delete=models.CASCADE, related_name='annuncio')
    utente = models.ForeignKey(User, on_delete=models.CASCADE)
    prezzo = models.IntegerField()
    accettata = models.BooleanField(null=True, blank=True)
    data_inserimento = models.DateTimeField(default=timezone.now, blank=True)

    def __str__(self):
        return f'{self.annuncio.marca} {self.annuncio.modello} - {self.prezzo}'

MotorMart/proposte/forms.py
from django import forms
from .models import Proposta
from annunci.models import Annuncio

class CreaProposta(forms.ModelForm):
    class Meta:
        model = Proposta
        fields = ['prezzo']

    def __init__(self, *args, **kwargs):
        self.annuncio = kwargs.pop('annuncio', None)
        super(CreaProposta, self).__init__(*args, **kwargs)

    def clean_prezzo(self):
        prezzo = self.cleaned_data.get('prezzo')
        if self.annuncio and prezzo >= self.annuncio.prezzo:
            self.add_error('prezzo', 'L\'anno deve essere un numero positivo.')
        return prezzo

    

MotorMart/proposte/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Proposta
from annunci.models import Annuncio
from .forms import CreaProposta


@login_required
def listing_detail(request, pk):
    annuncio = get_object_or_404(Annuncio, pk=pk)
    if request.method == 'POST':
        if 'submit_proposal' in request.POST:
            form = CreaProposta(request.POST, annuncio=annuncio)
            if form.is_valid():
                proposal = form.save(commit=False)

                if proposal.prezzo < annuncio.prezzo:
                    proposal.annuncio = annuncio
                    proposal.utente = request.user
                    proposal.save()
                    messages.success(request, "Proposta inviata")
                    return redirect('annunci:details', pk=pk)
                else:
                    messages.success(request, "Importo non valido")
                    return redirect('proposte:proposals', pk=pk)
            else:
                messages.error(request, "Errore nell'inserimento della proposta")
        return redirect('annunci:details', pk=pk)
    
    proposals = Proposta.objects.filter(annuncio=annuncio)
    form = CreaProposta(annuncio=annuncio)
    return render(request, 'proposte/proposta.html', {'listing': annuncio, 'form': form, 'proposals': proposals})

@login_required
def accept_proposal(request, proposal_id):
    proposal = get_object_or_404(Proposta, pk=proposal_id, annuncio__utente=request.user)
    proposal.accettata = True
    annuncio = get_object_or_404(Annuncio, pk=proposal.annuncio_id)
    annuncio.venduto = True
    annuncio.prezzo_acquisto = proposal.prezzo
    annuncio.compratore = proposal.utente.id
    annuncio.save()
    proposal.save()
    messages.success(request, "Proposta accettata")
    return redirect('annunci:details', pk=proposal.annuncio.pk)


@login_required
def reject_proposal(request, proposal_id):
    proposal = get_object_or_404(Proposta, pk=proposal_id, annuncio__utente=request.user)
    proposal.accettata = False
    proposal.save()
    messages.success(request, "Proposta rifiutata")
    return redirect('annunci:details', pk=proposal.annuncio.pk)

MotorMart/proposte/templates/proposte/proposta.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MotorMart - Proposta</title>
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href='{% static "./css/bootstrap.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/elegant-icons.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/nice-select.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/magnific-popup.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/jquery-ui.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/owl.carousel.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/slicknav.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "./css/style.css" %}' type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="{% url 'home' %}"><img src="{% static "./img/logo-new.png" %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-10">
                    <div class="header__nav">
                        <nav class="header__menu">
                            <ul>
                                {% if user.is_authenticated %}
                                    <li>Benvenuto, {{ user.username }}</li>
                                {% endif %}
                                <li><a href="{% url 'home' %}">Home</a></li>
                                <li><a href="{% url 'annunci:annunci_list' %}">Annunci</a></li>
                                <li><a href="{% url 'profile' %}">Profilo</a></li>
                                <li><a href="{% url 'chat:chat_list' %}">Chat</a></li>
                            </ul>
                        </nav>

                        {% if user.is_authenticated %}
                            <div class="header__nav__widget">
                                <form method="get" action="{% url 'annunci:create' %}">
                                    <button class="primary-btn">Crea annuncio</button>
                                </form>
                            </div>
                            <div class="header__nav__widget">
                                <form id="logout-form" method="post" action="{% url 'logout' %}">
                                    {% csrf_token %}
                                    <button class="primary-btn">Logout</button>
                                </form>
                            </div>
                        
                        {% else %}
                            <div class="header__nav__widget">
                                <a href="{% url 'login' %}" class="primary-btn">Login</a>
                                <a href="{% url 'register' %}" class="primary-btn">Registrazione</a>
                            </div>
                        {% endif %}

                    </div>
                </div>
            </div>
            <div class="canvas__open">
                <span class="fa fa-bars"></span>
            </div>
        </div>
    </header>
    <!-- Header Section End -->

    <!-- Hero Section Begin -->
    <section class="hero spad set-bg" data-setbg="{% static "./img/hero-bg-created.jpg" %}">
        <div class="container">
            <div class="row">
                
                <div class="col-lg-5">
                    <div class="hero__tab">
                        <ul class="nav nav-tabs" role="tablist">
                            
                            
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tabs-1" role="tabpanel">
                                <div class="hero__tab__form">
                                    
                                    <center>
                                        <h3 style="padding-bottom: 25px;">Proposte:</h3>
                                        {% if messages %}
                                            {% for m in messages %}
                                                <p>{{ m }}</p>
                                            {% endfor %}
                                        {% endif %}
                                        
                                        <!-- Only show proposals if the user is the listing owner -->
                                        {% if request.user == listing.utente %}
                                            {% for proposal in proposals %}
                                                <p>Prezzo proposto: {{ proposal.prezzo }} da {{ proposal.utente.username }}
                                                {% if proposal.accettata is None %}
                                                    {% if listing.venduto == None %}
                                                        <a href="{% url 'proposte:accept_proposal' proposal.id %}">Accetta</a>
                                                        <a href="{% url 'proposte:reject_proposal' proposal.id %}">Rifiuta</a>
                                                    {% endif %}
                                                {% elif proposal.accettata %}
                                                    <span>Accettata</span>
                                                {% else %}
                                                    <span>Rifiutata</span>
                                                {% endif %}
                                                </p>
                                            {% empty %}
                                                <p>Non ci sono proposte</p>
                                            {% endfor %}
                                        {% endif %}

                                        <!-- Allow non-owners to submit a proposal -->
                                        {% if request.user != listing.utente %}
                                            {% for proposal in proposals %}
                                                {% if request.user == proposal.utente %}
                                                    {% if proposal.accettata == None %}
                                                        <p>Prezzo proposto {{ proposal.prezzo }} - in attesa
                                                    {% endif %}
                                                    {% if proposal.accettata == True %}
                                                        <p>Prezzo proposto {{ proposal.prezzo }} - accettata
                                                    {% endif %}
                                                    {% if proposal.accettata == False %}
                                                        <p>Prezzo proposto {{ proposal.prezzo }} - rifiutata
                                                    {% endif %}
                                                {% endif %}
                                            {% endfor %}
                                            {% if listing.venduto == True %}
                                                <p>Automobile venduta
                                            {% else %}
                                            <form method="POST">
                                                {% csrf_token %}
                                                {{ form.as_p }}
                                                <button type="submit" name="submit_proposal">Invia proposta</button>
                                            </form>
                                            {% endif %}
                                        {% endif %}
                                      </center>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->

    <!-- Js Plugins -->
    <script src="{% static "./js/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "./js/bootstrap.min.js" %}"></script>
    <script src="{% static "./js/jquery.nice-select.min.js" %}"></script>
    <script src="{% static "./js/jquery-ui.min.js" %}"></script>
    <script src="{% static "./js/jquery.magnific-popup.min.js" %}"></script>
    <script src="{% static "./js/mixitup.min.js" %}"></script>
    <script src="{% static "./js/jquery.slicknav.js" %}"></script>
    <script src="{% static "./js/owl.carousel.min.js" %}"></script>
    <script src="{% static "./js/main.js" %}"></script>
</body>

</html>